spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greting-service:
  greeting: "Implementando"
  default-value: "Greeting QA"
